# Generated by Django 2.1.7 on 2019-03-17 01:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restful', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='history',
        ),
        migrations.AddField(
            model_name='game',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='snapshot',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), size=40), default=list, size=40),
        ),
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('PD', 'pending'), ('WN', 'won'), ('LT', 'lost')], default='PD', max_length=2),
        ),
    ]
