# Generated by Django 2.1.7 on 2019-03-17 01:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restful', '0002_auto_20190317_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='snapshot',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), default=list, size=40), default=list, size=40),
        ),
    ]
