# Generated by Django 2.1.7 on 2019-03-17 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restful', '0003_auto_20190317_0142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='score',
        ),
    ]
