# Generated by Django 2.1.7 on 2019-03-17 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restful', '0005_auto_20190317_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='duration',
        ),
    ]
