# Generated by Django 2.1.7 on 2019-03-17 19:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restful', '0006_remove_game_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='mine_num',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(1599), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='game',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='size_x',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(40), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='game',
            name='size_y',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(40), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
